Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-08, with the labels that each got.

#567 feat: remove binance onramp from buy screen
  .env.example
  src/app/screens/buy/index.tsx
  src/app/utils/constants.ts
  src/locales/en.json
Labels: Release 0.16.0

#574 chore: bump xverse-core to 1.6.2
  package-lock.json
  package.json
Labels: Release 0.17.0

#562 Fix incorrect swap transaction fee ticker
  package-lock.json
  src/app/screens/swap/swapConfirmation/feesBlock/index.tsx
  src/app/screens/swap/swapConfirmation/index.tsx
  src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx
  src/app/screens/swap/useSwap.tsx
Labels: ready for test

#524 Add ability to remove connected Ledger account
  src/app/components/accountHeader/index.tsx
  src/app/components/accountHeader/optionsDialog.tsx
  src/app/components/accountRow/index.tsx
  src/app/components/bottomModal/index.tsx
  src/app/components/optionsDialog/optionsDialog.tsx
  src/app/components/separator/index.tsx
  src/app/hooks/useWalletReducer.ts
  src/app/screens/accountList/index.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/app/screens/ledger/reviewLedgerStxTransaction/index.tsx
  src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
  src/app/screens/legalLinks/index.tsx
  src/app/screens/manageTokens/coinItem/index.tsx
  src/app/stores/index.ts
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/common/utils/ledger.ts
  src/locales/en.json
Labels: enhancement, Release 0.17.0, ready for release

#549 Support BTC message signing with ledger accounts
  .eslintrc.json
  src/app/components/confirmBtcTransactionComponent/inputOutputComponent.tsx
  src/app/components/confirmScreen/index.tsx
  src/app/components/ledger/connectLedgerView/index.tsx
  src/app/screens/authenticationRequest/index.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/ledger/confirmLedgerTransaction/index.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/utils/helper.ts
  src/app/utils/ledger.ts
  src/locales/en.json
Labels: enhancement, Release 0.17.0, ready for release

#575 chore: bump to 1.6.3-rc.1
  package-lock.json
  package.json
Labels: Release 0.17.0

#568 Filter out dead pending transactions
  src/app/screens/swap/useAlexSponsoredTransaction.ts
Labels: Release 0.18.0

#572 Display pending fungible token transactions in token dashboard
  src/app/components/transactions/transactionTitle.tsx
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
Labels: Release 0.18.0

#563 Show pending ordinal transactions
  package-lock.json
  package.json
  src/app/components/transactions/transactionAmount.tsx
  src/app/components/transactions/transactionStatusIcon.tsx
  src/app/components/transactions/transactionTitle.tsx
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
  src/locales/en.json
Labels: ready for release, Release 0.18.0

#581 feat: add Xverse namespaced providers
  src/inpage/index.ts
Labels: ready for release, Release 0.18.0

#570 Enable PSBT signing for ledger BTC accounts
  src/app/screens/signPsbtRequest/index.tsx
Labels: enhancement, Release 0.18.0
