Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-07, with the labels that each got.

#492 Allow multiple recipients for Ledger BTC send
  src/app/screens/confirmBtcTransaction/index.tsx
  src/app/screens/ledger/confirmLedgerTransaction/index.tsx
Labels: enhancement

#439 Allow send btc through sats connect
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/hooks/useSendBtcRequest.ts
  src/app/routes/index.tsx
  src/app/screens/btcSendScreen/index.tsx
  src/app/screens/confirmBtcTransaction/index.tsx
  src/app/utils/constants.ts
  src/common/types/inpage-types.ts
  src/common/types/message-types.ts
  src/common/utils/legacy-external-message-handler.ts
  src/common/utils/route-urls.ts
  src/content-scripts/content-script.ts
  src/inpage/sats.inpage.ts
  src/locales/en.json
Labels: sats-connect

#504 added text content null check in sendOrdinal
  src/app/screens/sendOrdinal/index.tsx
Labels: bug

#514 serialize stx transactions navigation params
  src/app/screens/confirmFtTransaction/index.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/sendFt/index.tsx
  src/app/screens/sendNft/index.tsx
  src/app/screens/sendStx/index.tsx
  src/app/screens/transactionRequest/index.tsx
Labels: bug

#520 Add custom ledger account name validation
  src/app/components/ledger/ledgerInput/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.tsx
Labels: enhancement

#519 Show wrong ledger device error
  src/app/screens/ledger/confirmLedgerTransaction/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/locales/en.json
Labels: enhancement

#521 The transaction history not showing a pending send transaction that was just sent from the address
  src/app/screens/coinDashboard/coinHeader.tsx
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
  src/locales/en.json
Labels: chore
