Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-09, with the labels that each got.

#587 fix: allow display of brc-20 if application/json type
  src/app/screens/ordinals/brc20Tile.tsx
  src/app/screens/ordinals/ordinalImage.tsx
Labels: ready for release

#577 fix: full screen and popup styling
  src/app/components/screenContainer/index.tsx
  src/pages/Options/index.css
  src/pages/Popup/index.css
  src/pages/Popup/index.tsx
Labels: ready for release, Release 0.18.0

#571 feat: add inscription confirmation for sats connect
  package-lock.json
  package.json
  src/app/components/accountHeader/index.tsx
  src/app/components/accountRow/index.tsx
  src/app/components/confirmScreen/index.tsx
  src/app/hooks/useBtcAddressRequest.ts
  src/app/routes/index.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/createInscription/CompleteScreen.tsx
  src/app/screens/createInscription/ContentLabel/common.ts
  src/app/screens/createInscription/ContentLabel/index.tsx
  src/app/screens/createInscription/ContentLabel/preview.tsx
  src/app/screens/createInscription/ContentLabel/utils.ts
  src/app/screens/createInscription/EditFee.tsx
  src/app/screens/createInscription/ErrorModal/index.tsx
  src/app/screens/createInscription/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinals/ordinalImage.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/utils/constants.ts
  src/common/types/inpage-types.ts
  src/common/types/message-types.ts
  src/common/utils/legacy-external-message-handler.ts
  src/common/utils/route-urls.ts
  src/content-scripts/content-script.ts
  src/inpage/sats.inpage.ts
  src/locales/en.json
Labels: Release 0.18.0

#564 Add STX support for Ledger accounts
  package-lock.json
  package.json
  src/app/components/bottomModal/index.tsx
  src/app/components/button/index.tsx
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/ledger/connectLedgerView/index.tsx
  src/app/components/ledger/ledgerAddressComponent/index.tsx
  src/app/components/ledger/ledgerAssetSelectCard/index.tsx
  src/app/components/ledger/reviewLedgerStxTransactionComponent/index.tsx
  src/app/components/receiveCardComponent/index.tsx
  src/app/components/transactionSetting/index.tsx
  src/app/hooks/useResetUserFlow.ts
  src/app/routes/index.tsx
  src/app/screens/authenticationRequest/index.tsx
  src/app/screens/coinDashboard/coinHeader.tsx
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/confirmBtcTransaction/index.tsx
  src/app/screens/confirmFtTransaction/index.tsx
  src/app/screens/confirmInscriptionRequest/index.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmOrdinalTransaction/index.tsx
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/ledger/addStxAddress/index.tsx
  src/app/screens/ledger/confirmLedgerTransaction/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.styled.ts
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/app/screens/ledger/ledgerSendFt/index.tsx
  src/app/screens/ledger/ledgerSendStx/index.tsx
  src/app/screens/ledger/reviewLedgerFtTransaction/index.tsx
  src/app/screens/ledger/reviewLedgerStxTransaction/index.tsx
  src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
  src/app/screens/nftDashboard/index.tsx
  src/app/screens/nftDashboard/receiveNft/index.tsx
  src/app/screens/onboarding/index.tsx
  src/app/screens/sendFt/index.tsx
  src/app/screens/sendNft/index.tsx
  src/app/screens/sendStx/index.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/utils/ledger.ts
  src/common/types/ledger.ts
  src/common/utils/ledger.ts
  src/locales/en.json
Labels: enhancement, returned, Release 0.18.0

#584 Fix Tx history screen reload & send form navigation issues
  src/app/components/sendForm/index.tsx
  src/app/components/sendForm/useClearFormOnAccountSwitch.ts
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/sendStx/index.tsx
Labels: ready for release

#580 Mismatch when verifying the addresses from the ledger device
  src/app/hooks/useResetUserFlow.ts
  src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
  src/locales/en.json
Labels: ready for test

#583 Handle min fee rate returned by the API
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/transactionSetting/editFee.tsx
  src/app/components/transactionSetting/editNonce.tsx
  src/app/components/transactionSetting/index.tsx
Labels: ready for release

#589 fix: don't show loader on balance refetch on home screen ENG-2757
  src/app/screens/home/balanceCard/index.tsx
  src/app/screens/home/index.tsx
Labels: ready for release

#585 feat: 1 step brc 20 transfers
  .eslintrc.json
  package-lock.json
  package.json
  src/app/components/accountHeader/index.tsx
  src/app/components/accountRow/index.tsx
  src/app/components/barLoader/index.tsx
  src/app/components/common.styled.ts
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/components/loadingTransactionStatus/circularSvgAnimation.tsx
  src/app/components/loadingTransactionStatus/index.tsx
  src/app/components/recipientComponent/index.tsx
  src/app/components/sendForm/index.tsx
  src/app/components/tabBar/index.tsx
  src/app/components/tokenImage/index.tsx
  src/app/components/transactionDetailComponent/index.tsx
  src/app/components/transactionSetting/editFee.tsx
  src/app/hooks/useBtcFeeRate.ts
  src/app/hooks/useResetUserFlow.ts
  src/app/routes/index.tsx
  src/app/screens/accountList/index.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/coinDashboard/coinHeader.tsx
  src/app/screens/confirmBrc20Transaction/brc20FeesComponent.tsx
  src/app/screens/confirmBrc20Transaction/editFees.tsx
  src/app/screens/confirmBrc20Transaction/index.tsx
  src/app/screens/confirmBtcTransaction/index.tsx
  src/app/screens/confirmInscriptionRequest/index.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmOrdinalTransaction/index.tsx
  src/app/screens/executeBrc20Transaction/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/ledger/addStxAddress/index.tsx
  src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
  src/app/screens/nftDetail/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/sendBrc20/brc20TransferForm.tsx
  src/app/screens/sendBrc20/brc20TransferInfo.tsx
  src/app/screens/sendBrc20/index.tsx
  src/app/screens/sendBrc20OneStep/brc20TransferForm.tsx
  src/app/screens/sendBrc20OneStep/index.tsx
  src/app/screens/sendBtc/index.tsx
  src/app/screens/sendNft/index.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/utils/brc20.ts
  src/app/utils/tokens.ts
  src/locales/en.json
  src/pages/Options/index.css
  src/pages/Popup/index.css
  src/theme/index.ts
Labels: BRC-20, ready for release

#582 Add scrollbar on all scrollable screens
  src/app/components/recipientComponent/index.tsx
  src/app/components/sendForm/index.tsx
  src/app/components/sendForm/useClearFormOnAccountSwitch.ts
  src/app/components/stepper/index.tsx
  src/app/components/transactions/txTransfers.tsx
  src/app/components/transactionsRequests/ContractCallRequest.tsx
  src/app/hooks/queries/useCoinData.ts
  src/app/hooks/queries/usePendingOrdinalTx.ts
  src/app/hooks/queries/useStackingData.ts
  src/app/hooks/queries/useStxPendingTxData.ts
  src/app/hooks/useSendBtcRequest.ts
  src/app/hooks/useWalletReducer.ts
  src/app/screens/accountList/index.tsx
  src/app/screens/btcSendScreen/index.tsx
  src/app/screens/createInscription/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/login/index.tsx
  src/app/screens/manageTokens/coinItem/index.tsx
  src/app/screens/ordinalDetail/ordinalAttributeComponent.tsx
  src/app/screens/restoreFunds/restoreBtc/index.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx
  src/app/screens/swap/useAlexSponsoredTransaction.ts
  src/pages/Popup/index.css
  src/theme/index.ts
Labels: ready for test

#603 fix: loader on home page issues
  src/app/components/accountRow/index.tsx
  src/app/hooks/useWalletReducer.ts
  src/app/screens/accountList/index.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/home/balanceCard/index.tsx
Labels: ready for release, Release 0.19.0

#609 Fix scrollbar in landing page
  src/pages/Popup/index.css
  src/theme/index.ts
Labels: ready for release, Release 0.19.0

#602 feat: notice for an non taproot address when sending brc 20 tokens
  package-lock.json
  package.json
  src/app/components/fiatAmountText/index.tsx
  src/app/components/loadingTransactionStatus/index.tsx
  src/app/components/sendForm/fiatRow.tsx
  src/app/components/sendForm/index.tsx
  src/app/screens/confirmBrc20Transaction/amountRow.tsx
  src/app/screens/confirmBrc20Transaction/editFees.tsx
  src/app/screens/confirmBrc20Transaction/index.tsx
  src/app/screens/confirmBrc20Transaction/recipientCard.tsx
  src/app/screens/sendBrc20OneStep/brc20TransferForm.tsx
  src/app/screens/sendBrc20OneStep/index.tsx
  src/app/ui-library/callout.tsx
  src/app/ui-library/common.styled.ts
  src/app/ui-library/inputFeedback.tsx
  src/app/utils/brc20.ts
  src/locales/en.json
  src/theme/index.ts
  tsconfig.json
Labels: ready for release, Release 0.19.0

#590 Build analytics tracking for web-extension
  .env.example
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/components/bottomModal/index.tsx
  src/app/hooks/useWalletReducer.ts
  src/app/routes/index.tsx
  src/app/screens/createWalletSuccess/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/legalLinks/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/settings/privacyPreferences/index.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/app/utils/constants.ts
  src/app/utils/mixpanel.ts
  src/assets/img/dashboard-icon.svg
  src/locales/en.json
Labels: ready for release, Release 0.20.0

#601 Handling fees with thresholds
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/hooks/queries/useFeeMultipliers.ts
  src/app/screens/confirmBrc20Transaction/index.tsx
  src/app/stores/wallet/actions/types.ts
  src/locales/en.json
Labels: ready for release

#586 Refactor ledger-related logic
  package-lock.json
  package.json
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/sendForm/index.tsx
  src/app/screens/authenticationRequest/index.tsx
  src/app/screens/ledger/addStxAddress/index.tsx
  src/app/screens/ledger/confirmLedgerTransaction/index.styled.ts
  src/app/screens/ledger/confirmLedgerTransaction/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.styled.ts
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/app/screens/ledger/importLedgerAccount/stepControls.tsx
  src/app/screens/ledger/importLedgerAccount/steps/index.styled.ts
  src/app/screens/ledger/importLedgerAccount/steps/index.tsx
  src/app/screens/ledger/importLedgerAccount/types.ts
  src/app/screens/ledger/verifyLedgerAccountAddress/index.styled.ts
  src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
  src/app/screens/onboarding/index.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/utils/constants.ts
  src/app/utils/ledger.ts
  src/locales/en.json
Labels: ready for release
