Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-12, with the labels that each got.

#699 Inject esplora provider into core functions
  package-lock.json
  package.json
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/components/transactionSetting/editFee.tsx
  src/app/hooks/queries/useTransactions.ts
  src/app/hooks/useBtcClient.ts
  src/app/hooks/useNonOrdinalUtxo.ts
  src/app/hooks/useOrdinalsByAddress.ts
  src/app/hooks/useSendBtcRequest.ts
  src/app/screens/confirmInscriptionRequest/index.tsx
  src/app/screens/createInscription/index.tsx
  src/app/screens/ledger/confirmLedgerTransaction/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/sendBrc20/index.tsx
  src/app/screens/sendBrc20OneStep/index.tsx
  src/app/screens/sendBtc/index.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/screens/sendRareSat/index.tsx
  src/app/screens/settings/changeNetwork/index.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/utils/helper.ts
Labels: ready for release, Release 0.26.0

#656 [ENG-3199] feat: Make UI for RBF in web-extension
  src/app/App.tsx
  src/app/components/bottomModal/index.tsx
  src/app/components/button/index.tsx
  src/app/components/transactionSetting/editFee.tsx
  src/app/components/transactionSetting/editNonce.tsx
  src/app/components/transactions/btcTransaction.tsx
  src/app/components/transactions/transactionTitle.tsx
  src/app/hooks/queries/useTransaction.ts
  src/app/hooks/useSponsoredTransaction.ts
  src/app/routes/index.tsx
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
  src/app/screens/confirmBrc20Transaction/editFees.tsx
  src/app/screens/nftDashboard/collectiblesTabs.tsx
  src/app/screens/nftDashboard/useNftDashboard.tsx
  src/app/screens/ordinalsCollection/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/speedUpTransaction/customFee.tsx
  src/app/screens/speedUpTransaction/index.styled.ts
  src/app/screens/speedUpTransaction/index.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/common/utils/legacy-external-message-handler.ts
  src/inpage/sats.inpage.ts
  src/locales/en.json
Labels: enhancement, ready for release, Release 0.26.0

#697 ENG-3383 Allow copy pasting entire seed phrase for developers only
  src/app/components/seedPhraseInput/index.tsx
Labels: ready for release

#709 [ENG-3427] fix: allow-404-get-utxos-from-psbt
  package-lock.json
  package.json
  src/app/hooks/useDetectOrdinalInSignPsbt.ts
Labels: ready for test, Release 0.27.0

#710 Fix account referencing issue on login
  src/app/components/guards/auth.tsx
  src/app/hooks/useWalletReducer.ts
Labels: ready for release, Release 0.27.0

#717 [ENG-3455] fix: Fix the sharp fee change on tx confirmation
  src/app/screens/confirmFtTransaction/index.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmStxTransaction/index.tsx
Labels: bug, ui

#725 Tim/eng 3475 nonce not updating correctly after switching accounts
  package-lock.json
  package.json
  src/app/components/transactionSetting/editNonce.tsx
  src/app/hooks/queries/useStxWalletData.ts
  src/app/screens/transactionRequest/index.tsx
  src/app/stores/wallet/reducer.ts
Labels: ready for release, Release 0.27.0

#652 Mahmoud/eng 3111 integrate with stacks raw hex signing on extension
  package-lock.json
  package.json
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/postCondition/postConditionView/index.tsx
  src/app/components/transactionSetting/editNonce.tsx
  src/app/components/transactionsRequests/ContractCallRequest.tsx
  src/app/components/transactionsRequests/ContractDeployTransaction.tsx
  src/app/hooks/queries/useStxPendingTxData.ts
  src/app/hooks/queries/useStxWalletData.ts
  src/app/hooks/useStxTransactionRequest.ts
  src/app/hooks/useTransationRequest.ts
  src/app/screens/confirmFtTransaction/index.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/sendFt/index.tsx
  src/app/screens/sendNft/index.tsx
  src/app/screens/sendStx/index.tsx
  src/app/screens/signatureRequest/clarityMessageView.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/screens/swap/useAlexSponsoredTransaction.ts
  src/app/screens/swap/useSwap.tsx
  src/app/screens/transactionRequest/helper.ts
  src/app/screens/transactionRequest/index.tsx
  src/app/stores/wallet/reducer.ts
  src/inpage/index.ts
  src/inpage/sats.inpage.ts
  src/inpage/stacks.inpage.ts
  webpack/webpack.config.js
Labels: ready for release, Release 0.27.0

#711 feat: add hook for confirmed btc balance, inscription callouts
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/hooks/queries/useConfirmedBtcBalance.ts
  src/app/screens/createInscription/index.tsx
  src/app/screens/sendStx/index.tsx
  src/app/screens/signatureRequest/clarityMessageView.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/screens/swap/useSwap.tsx
  src/locales/en.json
Labels: ready for release, Release 0.27.0
