Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-06, with the labels that each got.

#452 restore-ordinal-showing-wrong-ordinal
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/oridnalRow.tsx
Labels: bug

#390 Changes for mempool api
  package-lock.json
  package.json
  src/app/components/transactions/transactionRecipient.tsx
  src/app/utils/transactions/transactions.ts
Labels: enhancement

#454 remove clearing selected ordinal
  src/app/screens/ordinalDetail/index.tsx
Labels: bug

#444 Add validation error when BTC tx fee is higher than balance
  src/app/components/transactionSetting/editFee.tsx
  src/app/components/transactionSetting/index.tsx
  src/app/components/transferFeeView/index.tsx
Labels: bug

#458 Optimise the ordinals fetching to prevent 429 api rate limit
  package-lock.json
  package.json
  src/app/hooks/queries/ordinals/useAddressInscriptions.ts
  src/app/hooks/useTextOrdinalContent.ts
  src/app/screens/nftDashboard/index.tsx
  src/app/screens/ordinals/ordinalImage.tsx
Labels: bug

#462 Bug fix/refactor wallet state
  src/app/hooks/useWalletReducer.ts
  src/app/stores/index.ts
Labels: bug

#465 Fix ordinals recovery
  src/app/hooks/useTextOrdinalContent.ts
Labels: bug

#464 Migrate and clean up local storage data
  src/app/hooks/useCacheMigration.ts
  src/app/hooks/useWalletReducer.ts
  src/app/routes/index.tsx
  src/app/screens/login/index.tsx
  src/app/screens/migrationConfirmation/index.tsx
  src/app/screens/settings/index.tsx
  src/app/stores/index.ts
  src/assets/img/warningIcon.svg
  src/locales/en.json
  src/pages/Popup/index.tsx
Labels: enhancement

#461 Fix nft image issue
  package-lock.json
  package.json
  src/app/screens/nftDashboard/nft.tsx
  src/app/screens/nftDashboard/nftImage.tsx
  src/app/screens/ordinals/ordinalImage.tsx
Labels: bug

#457 fix for auto lock
  .env.example
  .eslintrc.json
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/components/guards/auth.tsx
  src/app/components/guards/session.tsx
  src/app/hooks/useWalletReducer.ts
  src/app/hooks/useWalletSession.ts
  src/app/routes/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/login/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/settings/lockCountdown/index.tsx
  src/app/stores/index.ts
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/app/utils/encryptionUtils.ts
  src/assets/img/settings/Timer.svg
  src/assets/img/settings/TimerFull.svg
  src/assets/img/settings/TimerHalf.svg
  src/background/background.ts
  src/inpage/sats.inpage.ts
  src/locales/en.json
  src/pages/Options/index.tsx
  src/pages/Popup/index.tsx
Labels: bug

#476 Add BRC-721E support
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinals/ordinalImage.tsx
Labels: enhancement

#460 Fix crash when stacks function call is missing arguments
  src/app/screens/transactionRequest/index.tsx
Labels: bug

#455 Detect invalid brc20 tokens
  package-lock.json
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinals/brc20Tile.tsx
Labels: enhancement, ui

#474 Detect and show all ordinals in sign PSBT
  src/app/hooks/useDetectOrdinalInSignPsbt.ts
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/signPsbtRequest/ordinalDetailComponent.tsx
Labels: bug

#472 Update PR description template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#371 chore/add-react-query-tooling
  .eslintrc.json
  package-lock.json
  package.json
  src/app/App.tsx
Labels: chore

#388 Display tokens data even if Xverse API is not responding
  src/app/hooks/queries/useCoinData.ts
  src/app/screens/manageTokens/index.tsx
Labels: bug

#491 Show receive alert pop up in specific screens only
  package-lock.json
  src/app/components/extendedScreenContainer/index.tsx
  src/app/components/receiveCardComponent/index.tsx
  src/app/components/screenContainer/index.tsx
  src/app/components/showBtcReceiveAlert/index.tsx
  src/app/components/showOrdinalReceiveAlert/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/nftDashboard/index.tsx
  src/app/screens/nftDashboard/receiveNft/index.tsx
  src/app/screens/receive/index.tsx
  src/app/stores/wallet/reducer.ts
Labels: bug
