Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-10, with the labels that each got.

#523 Show BRC20 token transaction history
  package-lock.json
  package.json
  src/app/components/transactions/btcTransaction.tsx
  src/app/components/transactions/transactionAmount.tsx
  src/app/components/transactions/transactionRecipient.tsx
  src/app/components/transactions/transactionStatusIcon.tsx
  src/app/components/transactions/transactionTitle.tsx
  src/app/hooks/queries/useTransactions.ts
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
  src/app/utils/transactions/transactions.ts
  src/locales/en.json
Labels: ready for release

#618 Tim/eng 2317 consistent dashboard buttons in extension
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/home/index.tsx
  src/assets/img/dashboard/swap.svg
  src/assets/img/icons/ArrowSwap.svg
Labels: ready for release

#615 Ledger send btc screen crash when going back and forward
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/screens/confirmBtcTransaction/index.tsx
Labels: ready for release

#614 Make `Authorize data collection` property turned on by default
  src/app/screens/legalLinks/index.tsx
  src/locales/en.json
Labels: ready for release

#619 [ENG-3059] fix: Remove ordinal callout from send rare sats
  src/app/components/sendForm/index.tsx
  src/app/hooks/queries/useAppConfig.ts
  src/app/screens/sendRareSat/index.tsx
  src/locales/en.json
Labels: ready for release

#621 feat: allow unpublished UTXOs as inputs to PSBTs
  src/app/hooks/useDetectOrdinalInSignPsbt.ts
Labels: ready for test

#510 Mahmoud/eng 2284 seedphrase vault
  package-lock.json
  package.json
  src/app/components/accountHeader/index.tsx
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/guards/auth.tsx
  src/app/components/guards/onboarding/index.tsx
  src/app/components/screenContainer/index.tsx
  src/app/components/seedPhraseView/index.tsx
  src/app/hooks/useSeedVault.ts
  src/app/hooks/useSendBtcRequest.ts
  src/app/hooks/useSignPsbtTx.ts
  src/app/hooks/useSignatureRequest.ts
  src/app/hooks/useWalletReducer.ts
  src/app/hooks/useWalletSession.ts
  src/app/routes/index.tsx
  src/app/screens/authenticationRequest/index.tsx
  src/app/screens/backupWallet/index.tsx
  src/app/screens/backupWalletSteps/index.tsx
  src/app/screens/confirmInscriptionRequest/index.tsx
  src/app/screens/createPassword/index.tsx
  src/app/screens/forgotPassword/index.tsx
  src/app/screens/login/index.tsx
  src/app/screens/nftDashboard/notice.tsx
  src/app/screens/restoreFunds/restoreBtc/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/sendBrc20/index.tsx
  src/app/screens/sendBtc/index.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/screens/sendRareSat/index.tsx
  src/app/screens/settings/backupWallet/index.tsx
  src/app/screens/settings/changePassword/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx
  src/app/screens/walletExists/index.tsx
  src/app/stores/index.ts
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/app/utils/chromeStorage.ts
  src/app/utils/encryptionUtils.ts
  src/app/utils/localStorage.ts
  src/background/background.ts
  src/common/utils/messageHandlers.ts
  src/manifest.json
  src/pages/Options/index.tsx
  src/pages/Popup/index.tsx
Labels: enhancement, testing

#624 [ENG-3115] fix: UI issue in the legal screen
  src/app/screens/legalLinks/index.tsx
Labels: ready for release, Release 0.22.0

#623 feat: add vout to the end of the tx id for unknown rarities
  .github/workflows/build.yml
  src/app/utils/rareSats.ts
Labels: ready for release, Release 0.22.0

#625 Fix minor UI issues
  src/app/components/sendForm/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/signatureRequest/index.tsx
Labels: ready for release, Release 0.22.0

#569 Handle gaia hub migration
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/app/components/sendForm/index.tsx
  src/app/screens/legalLinks/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/signatureRequest/index.tsx
  src/app/utils/rareSats.ts
Labels: ready for release, Release 0.22.0

#616 Migrate to using Testnet enabled Core version
  package-lock.json
  package.json
  src/app/components/sendForm/index.tsx
  src/app/components/transactionSetting/editFee.tsx
  src/app/components/transactionSetting/index.tsx
  src/app/hooks/queries/ordinals/useAddressInscriptionCollections.ts
  src/app/hooks/queries/ordinals/useAddressInscriptions.ts
  src/app/hooks/queries/ordinals/useAddressRareSats.ts
  src/app/hooks/queries/ordinals/useCollectionMarketData.ts
  src/app/hooks/queries/ordinals/useInscription.ts
  src/app/hooks/queries/useAppConfig.ts
  src/app/hooks/queries/useBtcCoinsBalance.ts
  src/app/hooks/queries/useCoinData.ts
  src/app/hooks/queries/useCoinRates.ts
  src/app/hooks/queries/useFeeMultipliers.ts
  src/app/hooks/queries/useStackingData.ts
  src/app/hooks/queries/useTransactions.ts
  src/app/hooks/useBtcFeeRate.ts
  src/app/hooks/useDetectOrdinalInSignPsbt.ts
  src/app/hooks/useOrdinalsApi.ts
  src/app/hooks/useOrdinalsByAddress.ts
  src/app/hooks/useTextOrdinalContent.ts
  src/app/screens/buy/index.tsx
  src/app/screens/confirmBrc20Transaction/index.tsx
  src/app/screens/createInscription/ContentLabel/index.tsx
  src/app/screens/createInscription/ErrorModal/index.tsx
  src/app/screens/createInscription/index.tsx
  src/app/screens/ordinalDetail/useOrdinalDetail.ts
  src/app/screens/ordinals/ordinalImage.tsx
  src/app/screens/rareSatsDetail/rareSatsDetail.tsx
  src/app/screens/sendBrc20OneStep/index.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/utils/brc20.ts
  src/app/utils/constants.ts
Labels: ready for test, Release 0.22.0

#628 fix: inscriptions and 1 step BRC-20 and seed vault (ENG-3125)
  package-lock.json
  package.json
  src/app/screens/createInscription/index.tsx
  src/app/screens/executeBrc20Transaction/index.tsx
Labels: ready for release, Release 0.22.0
