Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-11, with the labels that each got.

#657 fix: settings layover
  src/app/screens/settings/settingComponent/index.tsx
Labels: ready for release

#610 fix: remove bignumber from the redux store
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/components/confirmBtcTransactionComponent/inputOutputComponent.tsx
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/recipientComponent/index.tsx
  src/app/components/sendForm/index.tsx
  src/app/components/tokenTile/index.tsx
  src/app/components/transactionSetting/editFee.tsx
  src/app/components/transactionSetting/index.tsx
  src/app/components/transactionsRequests/ContractCallRequest.tsx
  src/app/components/transferFeeView/index.tsx
  src/app/hooks/queries/useBtcWalletData.ts
  src/app/hooks/useDetectOrdinalInSignPsbt.ts
  src/app/routes/index.tsx
  src/app/screens/btcSendScreen/index.tsx
  src/app/screens/coinDashboard/coinHeader.tsx
  src/app/screens/confirmBrc20Transaction/editFees.tsx
  src/app/screens/confirmBrc20Transaction/index.tsx
  src/app/screens/confirmBrc20Transaction/recipientCard.tsx
  src/app/screens/confirmInscriptionRequest/index.tsx
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/createInscription/CompleteScreen.tsx
  src/app/screens/restoreFunds/index.tsx
  src/app/screens/restoreFunds/restoreBtc/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/sendBrc20/index.tsx
  src/app/screens/sendBtc/index.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/swap/useCurrencyConversion.tsx
  src/app/stores/index.ts
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
Labels: ready for release

#660 feat: Enable Ledger PSBT signing
  package-lock.json
  package.json
  src/app/hooks/useDetectOrdinalInSignPsbt.ts
  src/app/screens/signPsbtRequest/index.tsx
Labels: ready for release, Release 0.23.0

#667 chore: bump sats-connect to 1.1.2
  package-lock.json
  package.json
Labels: ready for test, Release 0.23.0

#670 Replace hardcoded USD with dynamic NumericFormat prefix
  src/app/screens/swap/swapTokenBlock/index.tsx
Labels: bug, ui

#669 fix: fiat rates not fetching when user changed currency
  src/app/hooks/queries/ordinals/useAddressRareSats.ts
  src/app/hooks/queries/ordinals/useCollectionMarketData.ts
  src/app/hooks/queries/useCoinRates.ts
  src/app/hooks/useTextOrdinalContent.ts
Labels: Release 0.23.0

#634 feat: STX NFTs Tab
  .eslintrc.json
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/components/barLoader/index.tsx
  src/app/components/bundleAsset/bundleAsset.tsx
  src/app/components/collectibleCollage/collectibleCollage.tsx
  src/app/components/collectibleCollectionGridItem/index.tsx
  src/app/components/collectibleDetailTile/index.tsx
  src/app/components/optionsDialog/optionsDialog.tsx
  src/app/components/recipientAddressView/index.tsx
  src/app/components/sendForm/index.tsx
  src/app/components/tabBar/index.tsx
  src/app/components/tilesSkeletonLoader.tsx
  src/app/components/topRow/index.tsx
  src/app/hooks/queries/useBnsName.ts
  src/app/hooks/queries/useNftDetail.ts
  src/app/hooks/queries/useStacksCollectibles.ts
  src/app/hooks/stores/useNftReducer.ts
  src/app/hooks/stores/useOrdinalReducer.ts
  src/app/hooks/useResetUserFlow.ts
  src/app/layouts/sendLayout.tsx
  src/app/routes/index.tsx
  src/app/screens/coinDashboard/coinHeader.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmOrdinalTransaction/index.tsx
  src/app/screens/createInscription/CompleteScreen.tsx
  src/app/screens/home/index.tsx
  src/app/screens/nftCollection/index.tsx
  src/app/screens/nftCollection/useNftCollection.ts
  src/app/screens/nftDashboard/collectiblesTabs.tsx
  src/app/screens/nftDashboard/index.tsx
  src/app/screens/nftDashboard/inscriptionsTabGridItem.tsx
  src/app/screens/nftDashboard/nft.tsx
  src/app/screens/nftDashboard/nftImage.tsx
  src/app/screens/nftDashboard/nftTabGridItem.tsx
  src/app/screens/nftDashboard/receiveNft/index.tsx
  src/app/screens/nftDashboard/useNftDashboard.tsx
  src/app/screens/nftDetail/index.tsx
  src/app/screens/nftDetail/nftAttribute.tsx
  src/app/screens/nftDetail/useNftDetail.ts
  src/app/screens/ordinalDetail/useOrdinalDetail.ts
  src/app/screens/ordinalsCollection/index.tsx
  src/app/screens/rareSatsBundle/index.tsx
  src/app/screens/rareSatsDetail/rareSatsDetail.tsx
  src/app/screens/sendNft/index.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/transactionStatus/index.tsx
  src/app/stores/nftData/actions/actionCreator.ts
  src/app/stores/nftData/actions/types.ts
  src/app/stores/nftData/reducer.ts
  src/app/ui-library/snackBar.tsx
  src/app/utils/nfts.ts
  src/assets/img/nftDashboard/bns.svg
  src/assets/img/nftDashboard/ic_nft_diamond.svg
  src/assets/img/nftDashboard/nft_user.svg
  src/locales/en.json
  src/react-app-env.d.ts
Labels: testing, Release 0.23.0

#675 Hot/fix - migration for legacy users
  src/app/screens/login/index.tsx
  src/app/screens/migrationConfirmation/index.tsx
  src/locales/en.json
Labels: ready for test

#680 fix: use isInitialLoading so skeleton loader shows only if query is e…
  src/app/screens/nftDashboard/collectiblesTabs.tsx
  src/app/screens/nftDashboard/index.tsx
Labels: ready for release, Release 0.24.0

#679 fix: correctly parse bns names on testnet
  src/app/screens/nftDashboard/nft.tsx
  src/app/utils/constants.ts
  src/app/utils/nfts.ts
Labels: ready for release, Release 0.24.0

#687 [ENG-3314] feat: support repeat minter
  package-lock.json
  package.json
  src/app/routes/index.tsx
  src/app/screens/confirmBtcTransaction/index.tsx
  src/app/screens/createInscription/ContentLabel/index.tsx
  src/app/screens/createInscription/index.tsx
  src/app/utils/helper.ts
  src/common/types/inpage-types.ts
  src/common/types/message-types.ts
  src/common/utils/legacy-external-message-handler.ts
  src/common/utils/route-urls.ts
  src/content-scripts/content-script.ts
  src/inpage/sats.inpage.ts
  src/locales/en.json
Labels: Release 0.25.0
