Repository secretkeylabs/xverse-web-extension, pull requests merged in 2023-05, with the labels that each got.

#427 Fix crash for recover ordinal
  package-lock.json
  package.json
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/oridnalRow.tsx
Labels: bug

#433 fix for structured message signing
  package-lock.json
  package.json
  src/app/hooks/useSignatureRequest.ts
Labels: bug

#432 Increase size of extension bar icon
  src/assets/img/xverse_icon.png
Labels: enhancement

#431 Open the Edit fees popup straight away for BTC txs
  src/app/components/confirmBtcTransactionComponent/index.tsx
  src/app/components/confirmStxTransactionComponent/index.tsx
  src/app/components/transactionSetting/index.tsx
Labels: bug

#420 Feat/brc 20 transfer
  src/app/components/sendForm/index.tsx
  src/app/components/tokenTile/index.tsx
  src/app/routes/index.tsx
  src/app/screens/coinDashboard/coinHeader.tsx
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/confirmBtcTransaction/index.tsx
  src/app/screens/confirmInscriptionRequest/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinalDetail/ordinalAttributeComponent.tsx
  src/app/screens/ordinals/brc20Tile.tsx
  src/app/screens/ordinals/ordinalImage.tsx
  src/app/screens/sendBrc20/brc20TransferForm.tsx
  src/app/screens/sendBrc20/brc20TransferInfo.tsx
  src/app/screens/sendBrc20/index.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/screens/signatureRequest/collapsableContainer.tsx
  src/app/screens/transactionStatus/index.tsx
  src/app/utils/constants.ts
  src/assets/img/nftDashboard/ArrowUpRight.svg
  src/assets/img/nftDashboard/Printer.svg
  src/assets/img/nftDashboard/RocketLaunch.svg
  src/locales/en.json
Labels: BRC-20

#430 Improve the password strength check
  package-lock.json
  package.json
  src/app/components/passwordInput/index.tsx
  src/app/screens/createPassword/index.tsx
  src/app/screens/settings/backupWallet/index.tsx
  src/app/screens/settings/changePassword/index.tsx
  src/app/screens/settings/index.tsx
  src/locales/en.json
Labels: enhancement

#447 Fix spacing and alignment issue in Contract call Transaction screen
  src/app/components/transactionDetailComponent/index.tsx
  src/app/components/transactionsRequests/ContractCallRequest.tsx
Labels: bug, ui

#424 fix: reset Copied text back to default value after a timeout
  src/app/components/accountRow/index.tsx
Labels: bug, ui, contributor

#450 Fix ordinal dashboard crash
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinals/brc20Tile.tsx
Labels: bug, BRC-20
