Repository secretkeylabs/xverse-web-extension, pull requests merged in 2024-01, with the labels that each got.

#720 [ENG-3471] feat: use estimated fees for stx transactions
  package-lock.json
  package.json
  src/app/screens/confirmFtTransaction/index.tsx
  src/app/screens/confirmNftTransaction/index.tsx
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/sendFt/index.tsx
  src/app/screens/sendNft/index.tsx
  src/app/screens/sendStx/index.tsx
  src/app/screens/transactionRequest/index.tsx
Labels: ready for release, release 0.28.0

#712 [ENG-3436] chore: Make some code refactoring for RBF in the extension
  src/app/screens/confirmBrc20Transaction/editFees.tsx
  src/app/screens/nftCollection/index.tsx
  src/app/screens/nftDetail/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinalsCollection/index.tsx
  src/app/screens/speedUpTransaction/customFee.tsx
  src/app/screens/speedUpTransaction/customFee/index.styled.ts
  src/app/screens/speedUpTransaction/customFee/index.tsx
  src/app/screens/speedUpTransaction/index.styled.ts
  src/app/screens/speedUpTransaction/index.tsx
  src/app/screens/swap/swapInfoBlock/index.tsx
  src/app/screens/swap/swapTokenBlock/index.tsx
  src/app/utils/constants.ts
  src/app/utils/helper.ts
  src/locales/en.json
Labels: chore, ready for release, release 0.28.0

#726 feat: add btc consolidation logic and new ui components to psbt and batch psbt screens
  package-lock.json
  package.json
  src/app/components/confirmBtcTransaction/index.tsx
  src/app/components/confirmBtcTransaction/itemRow/amount.tsx
  src/app/components/confirmBtcTransaction/itemRow/amountWithInscriptionSatribute.tsx
  src/app/components/confirmBtcTransaction/itemRow/bundleTxView.tsx
  src/app/components/confirmBtcTransaction/itemRow/inscription.tsx
  src/app/components/confirmBtcTransaction/itemRow/inscriptionSatributeRow.tsx
  src/app/components/confirmBtcTransaction/itemRow/rareSats.tsx
  src/app/components/confirmBtcTransaction/receiveSection.tsx
  src/app/components/confirmBtcTransaction/transactionSummary.tsx
  src/app/components/confirmBtcTransaction/transferSection.tsx
  src/app/components/confirmBtcTransaction/txInOutput/transactionInput.tsx
  src/app/components/confirmBtcTransaction/txInOutput/transactionOutput.tsx
  src/app/components/confirmBtcTransaction/txInOutput/txInOutput.tsx
  src/app/components/confirmBtcTransaction/utils.ts
  src/app/components/confirmBtcTransactionComponent/bundle.tsx
  src/app/components/confirmBtcTransactionComponent/bundleItem.tsx
  src/app/components/screenContainer/index.tsx
  src/app/components/transferFeeView/index.tsx
  src/app/hooks/useSignPsbtTx.ts
  src/app/hooks/useTransactionContext.ts
  src/app/screens/ordinals/ordinalImage.tsx
  src/app/screens/signBatchPsbtRequest/index.tsx
  src/app/screens/signPsbtRequest/bundleItemsComponent.tsx
  src/app/screens/signPsbtRequest/index.tsx
  src/app/screens/signPsbtRequest/tempMockDataUtil.ts
  src/app/screens/signPsbtRequest/useSignPsbtValidationGate.ts
  src/app/screens/speedUpTransaction/index.tsx
  src/app/ui-library/avatar.tsx
  src/app/ui-library/callout.tsx
  src/app/ui-library/divider.tsx
  src/assets/img/rareSats/ic_ordinal_small_over_card.svg
  src/assets/img/rareSats/link.svg
  src/locales/en.json
  src/pages/Popup/index.css
  src/pages/Popup/index.html
Labels: enhancement, ready for release, release 0.28.0

#738 [ENG-3496] fix: utxo 500 issue add a fallback option to our api httpsbtc
  package-lock.json
  package.json
  src/app/hooks/queries/useAppConfig.ts
  src/app/hooks/useBtcClient.ts
  src/app/hooks/useNetwork.ts
  src/app/hooks/useWalletReducer.ts
  src/app/screens/settings/changeNetwork/index.tsx
  src/app/screens/settings/changeNetwork/networkRow.tsx
  src/app/screens/settings/changeNetwork/nodeInput.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/app/utils/constants.ts
  src/locales/en.json
  tsconfig.json
Labels: ready for test, release 0.28.0

#736 chore: add new auto lock period values and migrate users if needed
  src/app/hooks/useWalletReducer.ts
  src/app/hooks/useWalletSession.ts
  src/app/screens/settings/lockCountdown/index.tsx
  src/app/stores/wallet/actions/types.ts
  src/assets/img/settings/Timer.svg
  src/assets/img/settings/Timer15m.svg
  src/assets/img/settings/Timer1h.svg
  src/assets/img/settings/Timer30m.svg
  src/assets/img/settings/Timer3h.svg
  src/assets/img/settings/TimerFull.svg
  src/assets/img/settings/TimerHalf.svg
  src/locales/en.json
Labels: ready for test, release 0.28.0

#688 Allow testnet ledger accounts
  src/app/hooks/useWalletReducer.ts
  src/app/screens/accountList/index.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/app/screens/settings/index.tsx
  src/app/screens/speedUpTransaction/index.tsx
  src/common/utils/ledger.ts
Labels: enhancement, ready for test, release 0.28.0

#727 [ENG-3474] feat: Make UI for STX RBF in the extension
  src/app/components/confirmBtcTransaction/itemRow/rareSats.tsx
  src/app/components/confirmBtcTransaction/txInOutput/transactionOutput.tsx
  src/app/components/speedUpTransaction/btc.tsx
  src/app/components/speedUpTransaction/index.styled.ts
  src/app/components/speedUpTransaction/stx.tsx
  src/app/components/transactions/btcTransaction.tsx
  src/app/components/transactions/stxTransaction.tsx
  src/app/components/transactions/stxTransferTransaction.tsx
  src/app/hooks/queries/useTransaction.ts
  src/app/hooks/useRbfTransactionData.ts
  src/app/hooks/useWalletReducer.ts
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/app/screens/speedUpTransaction/customFee/index.styled.ts
  src/app/screens/speedUpTransaction/customFee/index.tsx
  src/app/screens/speedUpTransaction/index.styled.ts
  src/app/screens/speedUpTransaction/index.tsx
  src/assets/img/transactions/increaseFee.svg
  src/locales/en.json
Labels: enhancement, ready for test, release 0.28.0

#749 [ENG-3564] fix: Speed up transaction ui issue displaying and loading
  src/app/hooks/useRbfTransactionData.ts
Labels: bug, release 0.28.0

#748 [ENG-3563] fix: BTC fee infinite loader when sending ordinals
  src/app/components/transactionSetting/editBtcFee.tsx
  src/app/components/transactionSetting/feeItem.tsx
  src/app/hooks/useBtcFees.ts
Labels: bug, release 0.28.0

#754 Fix indent on the Settings screen
  src/app/screens/settings/settingComponent/index.tsx
Labels: bug, ui

#700 ENG-2696: Fix restore seed phrase screen scroll
  src/app/components/extendedScreenContainer/index.tsx
  src/app/components/seedPhraseInput/index.tsx
  src/app/screens/restoreWallet/enterSeedphrase.tsx
  src/app/screens/restoreWallet/index.tsx
  src/pages/Options/index.css
Labels: ready for test

#759 [ENG-3581] fix: set default fallbackbtcapiurl state on update
  src/app/stores/index.ts
  src/app/stores/wallet/reducer.ts
Labels: Release 0.28.1

#757 ENG-3498: Control STX display via Manage Tokens Screen
  src/app/components/postCondition/stxPostConditionCard.tsx
  src/app/components/tokenImage/index.tsx
  src/app/components/tokenTile/index.tsx
  src/app/components/topRow/index.tsx
  src/app/hooks/useWalletReducer.ts
  src/app/screens/confirmStxTransaction/index.tsx
  src/app/screens/home/balanceCard/index.tsx
  src/app/screens/home/coinSelectModal/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/ledger/addStxAddress/index.tsx
  src/app/screens/ledger/importLedgerAccount/steps/index.tsx
  src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
  src/app/screens/manageTokens/coinItem/index.tsx
  src/app/screens/manageTokens/index.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/assets/img/dashboard/stack_icon.svg
  src/assets/img/dashboard/stacks_token.svg
  src/assets/img/dashboard/stx_icon.svg
  src/locales/en.json
Labels: ready for test

#762 fix: wrong variable used in validation to show top divider for first asset item in receive in payment section component
  src/app/components/confirmBtcTransaction/receiveSection.tsx
Labels: ready for release, Release 0.29.0

#755 fix: rare sats icon shape and remove extra props from rare sat icon component
  src/app/components/confirmBtcTransactionComponent/bundleItem.tsx
  src/app/components/rareSatAsset/rareSatAsset.tsx
  src/app/components/rareSatIcon/rareSatIcon.tsx
  src/app/screens/nftDashboard/rareSatsTabGridItem.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/rareSatsBundle/rareSatsBundleGridItem.tsx
  src/assets/img/nftDashboard/rareSats/1Dpali.png
  src/assets/img/nftDashboard/rareSats/1stx.png
  src/assets/img/nftDashboard/rareSats/2Dpali.png
  src/assets/img/nftDashboard/rareSats/3Dpali.png
  src/assets/img/nftDashboard/rareSats/alpha.png
  src/assets/img/nftDashboard/rareSats/b286.png
  src/assets/img/nftDashboard/rareSats/b78.png
  src/assets/img/nftDashboard/rareSats/b9.png
  src/assets/img/nftDashboard/rareSats/b9450.png
  src/assets/img/nftDashboard/rareSats/black_epic.png
  src/assets/img/nftDashboard/rareSats/black_epic.svg
  src/assets/img/nftDashboard/rareSats/black_legendary.png
  src/assets/img/nftDashboard/rareSats/black_legendary.svg
  src/assets/img/nftDashboard/rareSats/black_rare.png
  src/assets/img/nftDashboard/rareSats/black_rare.svg
  src/assets/img/nftDashboard/rareSats/black_uncommon.png
  src/assets/img/nftDashboard/rareSats/black_uncommon.svg
  src/assets/img/nftDashboard/rareSats/common.svg
  src/assets/img/nftDashboard/rareSats/epic.png
  src/assets/img/nftDashboard/rareSats/epic.svg
  src/assets/img/nftDashboard/rareSats/fibonacci.png
  src/assets/img/nftDashboard/rareSats/hitman.png
  src/assets/img/nftDashboard/rareSats/jpeg.png
  src/assets/img/nftDashboard/rareSats/legendary.png
  src/assets/img/nftDashboard/rareSats/legendary.svg
  src/assets/img/nftDashboard/rareSats/mythic.png
  src/assets/img/nftDashboard/rareSats/mythic.svg
  src/assets/img/nftDashboard/rareSats/nakamoto.png
  src/assets/img/nftDashboard/rareSats/namepali.png
  src/assets/img/nftDashboard/rareSats/new_feature.svg
  src/assets/img/nftDashboard/rareSats/omega.png
  src/assets/img/nftDashboard/rareSats/pali.png
  src/assets/img/nftDashboard/rareSats/paliblock.png
  src/assets/img/nftDashboard/rareSats/perfectpaliception.png
  src/assets/img/nftDashboard/rareSats/pizza.png
  src/assets/img/nftDashboard/rareSats/rare.png
  src/assets/img/nftDashboard/rareSats/rare.svg
  src/assets/img/nftDashboard/rareSats/seqpali.png
  src/assets/img/nftDashboard/rareSats/silkroad.png
  src/assets/img/nftDashboard/rareSats/uncommon.png
  src/assets/img/nftDashboard/rareSats/uncommon.svg
  src/assets/img/nftDashboard/rareSats/unknown.png
  src/assets/img/nftDashboard/rareSats/unknown.svg
  src/assets/img/nftDashboard/rareSats/vintage.png
Labels: ready for release, Release 0.29.0

#763 chore: use new core version with btc signer version upgrade
  package-lock.json
  package.json
  src/app/hooks/useRbfTransactionData.ts
  src/app/screens/speedUpTransaction/index.tsx
Labels: ready for test, Release 0.29.0

#740 [ENG-3036] feat: Rename accounts from the change account screen
  src/app/components/accountHeader/index.tsx
  src/app/components/accountRow/index.tsx
  src/app/components/ledger/ledgerInput/index.tsx
  src/app/components/topRow/index.tsx
  src/app/hooks/useWalletReducer.ts
  src/app/layouts/sendLayout.tsx
  src/app/screens/accountList/index.tsx
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/ledger/importLedgerAccount/index.tsx
  src/app/screens/ledger/importLedgerAccount/stepControls.tsx
  src/app/screens/nftCollection/index.tsx
  src/app/screens/nftDetail/index.tsx
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinalsCollection/index.tsx
  src/app/screens/speedUpTransaction/index.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/app/utils/constants.ts
  src/app/utils/helper.ts
  src/locales/en.json
Labels: enhancement, ready for release, Release 0.29.0

#765 [ENG-3614] feat: Ability to manage a BRC-20 token's visibility (hide)
  package-lock.json
  package.json
  src/app/components/fiatAmountText/index.tsx
  src/app/components/tokenImage/index.tsx
  src/app/components/tokenTile/index.tsx
  src/app/hooks/queries/useBtcCoinsBalance.ts
  src/app/screens/coinDashboard/index.tsx
  src/app/screens/home/balanceCard/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/manageTokens/coinItem/index.tsx
  src/app/screens/manageTokens/index.tsx
Labels: ready for release, Release 0.29.0

#768 Fix typing between sats connect and extension for providers
  package-lock.json
  package.json
  src/inpage/index.ts
Labels: Release 0.29.0

#756 [ENG-3513] feat: View accounts balances in the Change Account screen
  src/app/components/accountRow/index.tsx
  src/app/components/accountRow/lazyAccountRow.tsx
  src/app/hooks/queries/useAccountBalance.ts
  src/app/hooks/queries/useBtcCoinsBalance.ts
  src/app/hooks/queries/useCoinData.ts
  src/app/hooks/useIntersectionObserver.ts
  src/app/screens/accountList/index.tsx
  src/app/screens/home/balanceCard/index.tsx
  src/app/screens/home/index.tsx
  src/app/screens/manageTokens/index.tsx
  src/app/screens/swap/swapConfirmation/stxInfoBlock/index.tsx
  src/app/stores/wallet/actions/actionCreators.ts
  src/app/stores/wallet/actions/types.ts
  src/app/stores/wallet/reducer.ts
  src/app/utils/helper.ts
Labels: enhancement, ready for release, Release 0.29.0

#715 [ENG-3370] feat: improve get address screen
  package-lock.json
  package.json
  src/app/hooks/useBtcAddressRequest.ts
  src/app/routes/index.tsx
  src/app/screens/accountList/index.tsx
  src/app/screens/btcSelectAddressScreen/accountView.tsx
  src/app/screens/btcSelectAddressScreen/index.tsx
  src/app/screens/connect/addressPurposeBox.tsx
  src/app/screens/connect/authenticationRequest/index.tsx
  src/app/screens/connect/btcSelectAddressScreen/helper.ts
  src/app/screens/connect/btcSelectAddressScreen/index.tsx
  src/app/screens/connect/permissionsList.tsx
  src/app/screens/connect/selectAccount.tsx
  src/assets/img/webInteractions/authPlaceholder.svg
  src/inpage/index.ts
  src/locales/en.json
Labels: testing, Release 0.29.0

#776 bug-fix/confirm-passoword-button
  src/app/screens/createPassword/index.tsx
Labels: bug

#783 fix: reset balance state between change accounts
  src/app/stores/wallet/reducer.ts
Labels: ready for release, Release 0.29.0
