Repository secretkeylabs/xverse-web-extension, pull requests merged in 2024-02, with the labels that each got.

#785 Ensure translations are not applied to seed phrases
  src/app/components/seedPhraseView/index.tsx
  src/app/components/seedPhraseView/word.tsx
  src/app/screens/backupWalletSteps/verifySeed.tsx
Labels: ready for release, 0.29.1

#786 replace deprecated util with core
  package-lock.json
  package.json
  src/app/screens/connect/btcSelectAddressScreen/helper.ts
  src/app/screens/connect/btcSelectAddressScreen/index.tsx
Labels: ready for release, 0.29.1

#787 Remove fee subtraction from the You Will Transfer total - ENG-3699
  src/app/components/confirmBtcTransaction/transactionSummary.tsx
Labels: ready for release, 0.29.1

#784 update ledger message signing util
  package-lock.json
  package.json
  src/app/screens/signatureRequest/index.tsx
  src/app/utils/ledger.ts
Labels: 0.29.1

#790 bug-fix/app-icon-fetching-failure
  src/app/screens/connect/btcSelectAddressScreen/index.tsx
Labels: bug

#766 Send btc integrate with tx consolidation logic
  package-lock.json
  package.json
  src/app/components/accountRow/index.tsx
  src/app/components/button/index.tsx
  src/app/components/confirmBtcTransaction/index.tsx
  src/app/components/confirmBtcTransaction/transactionSummary.tsx
  src/app/components/confirmBtcTransaction/transferSection.tsx
  src/app/components/speedUpTransaction/btc.tsx
  src/app/components/transactionSetting/editBtcFee.tsx
  src/app/components/transactionSetting/feeItem.tsx
  src/app/components/transferFeeView/index.tsx
  src/app/routes/index.tsx
  src/app/screens/btcSendScreen/index.tsx
  src/app/screens/buy/index.tsx
  src/app/screens/coinDashboard/transactionsHistoryList.tsx
  src/app/screens/confirmBrc20Transaction/editFees.tsx
  src/app/screens/connect/btcSelectAddressScreen/index.tsx
  src/app/screens/createInscription/EditFee.tsx
  src/app/screens/createInscription/index.tsx
  src/app/screens/home/balanceCard/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/ordinalRow.tsx
  src/app/screens/sendBtc/amountSelector.tsx
  src/app/screens/sendBtc/helpers.ts
  src/app/screens/sendBtc/index.tsx
  src/app/screens/sendBtc/recipientSelector.tsx
  src/app/screens/sendBtc/stepDisplay.tsx
  src/app/screens/sendBtc/steps.tsx
  src/app/screens/signBatchPsbtRequest/index.tsx
  src/app/screens/speedUpTransaction/customFee/index.tsx
  src/app/screens/speedUpTransaction/index.tsx
  src/app/screens/stacking/index.tsx
  src/app/screens/transactionRequest/index.tsx
  src/app/ui-components/btcAmountSelector.tsx
  src/app/ui-components/selectFeeRate/feeItem.tsx
  src/app/ui-components/selectFeeRate/feeSelectPopup.tsx
  src/app/ui-components/selectFeeRate/index.tsx
  src/app/ui-library/button.tsx
  src/app/ui-library/common.styled.ts
  src/app/ui-library/input.tsx
  src/app/ui-library/inputFeedback.tsx
  src/app/ui-library/sheet.tsx
  src/app/ui-library/spinner.tsx
  src/locales/en.json
  src/theme/index.ts
  tsconfig.json
  vite.config.js
Labels: ready for release, Release 0.30.0

#777 [ENG-3609] fix: ordinal image should fall back to the ordiview thumbnail
  src/app/screens/createInscription/ContentLabel/index.tsx
  src/app/screens/createInscription/ContentLabel/utils.ts
  src/app/screens/ordinalDetail/index.tsx
  src/app/screens/ordinalDetail/useOrdinalDetail.ts
  src/app/screens/ordinals/brc20Tile.tsx
  src/app/screens/ordinals/ordinalImage.tsx
  src/app/utils/brc20.ts
  src/locales/en.json
Labels: ready for release, Release 0.30.0

#791 [ENG-3193] refactor: Refactor away from selectedOrdinal
  src/app/components/collectibleCollectionGridItem/index.tsx
  src/app/hooks/queries/ordinals/useAddressInscription.ts
  src/app/hooks/stores/useOrdinalReducer.ts
  src/app/screens/confirmOrdinalTransaction/index.tsx
  src/app/screens/nftCollection/index.tsx
  src/app/screens/ordinalDetail/useOrdinalDetail.ts
  src/app/screens/ordinals/index.tsx
  src/app/screens/ordinalsCollection/index.tsx
  src/app/screens/rareSatsBundle/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/index.tsx
  src/app/screens/restoreFunds/restoreOrdinals/ordinalRow.tsx
  src/app/screens/sendOrdinal/index.tsx
  src/app/stores/nftData/actions/actionCreator.ts
  src/app/stores/nftData/actions/types.ts
  src/app/stores/nftData/reducer.ts
Labels: ready for release, Release 0.30.0

#806 chore: bump core to v11.1.1
  package-lock.json
  package.json
Labels: ready for test
